module.exports = {
    auth: require('./users/auth'),
    signup: require('./users/signup'),
    signout: require('./users/signout'),
    logout: require('./users/logout'),
    login: require('./users/login'),
    editprofile: require('./users/editprofile'),
    getusers: require('./users/getusers'),
    createpost: require('./posts/createpost'),
    deletepost: require('./posts/deletepost'),
    getonepost: require('./posts/getonepost'),
    getallposts: require('./posts/getallposts'),
    mypost: require('./posts/mypost'),
    patchpost: require('./posts/patchpost'),
    gettags: require('./tags/gettags'),
    getpostsbytags: require('./tags/getpostsbytags'),
    createcomment: require('./comments/createcomment'),
    deletecomment: require('./comments/deletecomment'),
    getcomments: require('./comments/getcomments'),
    patchcomment: require('./comments/patchcomment'),
    addlikes: require('./likes/addlikes'),
    deletelikes: require('./likes/deletelikes'),
    getlikes: require('./likes/getlikes'),
    kakaologin: require('./kakao/kakaologin'),
}